// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/header";
import Category from "./Components/category";
import Info from "./Components/info";
import HeroSlider from "./Components/heroslider";
import Footer from "./Components/footer";
import Navbar from "./Components/navbar";
import Post from "./Components/post";
import FeaturedPosts from "./Components/featurepost";
import Traveltips from "./Components/traveltips";

// Load fonts with static variable names
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap", // ensures font loads consistently
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Mark this as a server component (default) but keep fonts static
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning // avoids hydration warnings
      >
        <Header/>
        <div className="my-8" />
        <Navbar/>
        <div className="my-8" />
        <HeroSlider />
        <FeaturedPosts/>
        <Traveltips/>
        <Post/>
        <Info />
        <Category />
        <Footer/>
        {children}
      </body>
    </html>
  );
}
